(test
 (name test_cwr)
 (modules test_cwr)
 (libraries cabal_workflow_runner alcotest eio eio_main)
 (deps
  (glob_files %{project_root}/examples/*.json)
  (glob_files %{project_root}/schema/*.json)))

(test
 (name test_attestation)
 (modules test_attestation)
 (libraries cabal_workflow_runner alcotest eio eio_main unix))

(test
 (name test_pcc)
 (modules test_pcc)
 (libraries cabal_workflow_runner alcotest eio eio_main)
 (deps
  (glob_files %{project_root}/examples/*.json)))

(rule
 (alias runtest)
 (deps test_approval_ledger.sh)
 (action (run bash %{dep:test_approval_ledger.sh} %{exe:../bin/main.exe})))
